title: "My Vite-Powered Jekyll Site"
description: "React front-end bundled with Vite, served by Jekyll"
markdown: kramdown
theme: minima

# Where Jekyll should look for the final Vite bundle (copied in step 4 above)
include:
  - dist

# Ignore vendor folders so gem scaffolds are never processed
exclude:
  - .bundle
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - vite.config.js
