version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_KEY=${API_KEY}
        - AUTH_DOMAIN=${AUTH_DOMAIN}
        - PROJECT_ID=${PROJECT_ID}
        - STORAGE_BUCKET=${STORAGE_BUCKET}
        - MESSAGING_SENDER_ID=${MESSAGING_SENDER_ID}
        - APP_ID=${APP_ID}
        - MEASUREMENT_ID=${MEASUREMENT_ID}
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - NUXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

