import { AgGridReact } from "ag-grid-react";
import { useEffect, useMemo, useState } from "react";
import "ag-grid-community/styles/ag-grid.css";
import "ag-grid-community/styles/ag-theme-alpine.css";
import {
  ModuleRegistry,
  AllCommunityModule,
  _isMultiRowSelection,
} from "ag-grid-community";
import "./Inventory.css";
import { LocalizationProvider } from "@mui/x-date-pickers";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import { DatePicker } from "@mui/x-date-pickers/DatePicker";
import dayjs from "dayjs";

ModuleRegistry.registerModules([AllCommunityModule]);
const inventoryRows = [
  {
    itemName: "Boba-Brown (6/box)",
    weekStart: 43,
    inventoryAdded: 42,
    weekEnd: 44,
    order: 41,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Boba-White (6/box)",
    weekStart: 21,
    inventoryAdded: 18,
    weekEnd: 25,
    order: 14,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Cream Pudding Powder (20/box)",
    weekStart: 15,
    inventoryAdded: null,
    weekEnd: 10,
    order: 5,
    amount: null,
    boxes: 20,
  },
  {
    itemName: "Mochi Powder (20/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 20,
  },
  {
    itemName: "Cheese Foam Powder (20/box)",
    weekStart: 12,
    inventoryAdded: 20,
    weekEnd: 32,
    order: 0,
    amount: null,
    boxes: 20,
  },
  {
    itemName: "Pudding Powder (20/box)",
    weekStart: 35,
    inventoryAdded: null,
    weekEnd: 29,
    order: 6,
    amount: null,
    boxes: 20,
  },
  {
    itemName: "Casava/Starch Powder (20/box)",
    weekStart: 20,
    inventoryAdded: null,
    weekEnd: 20,
    order: 0,
    amount: null,
    boxes: 20,
  },
  {
    itemName: "Plain Jelly Powder (10/box)",
    weekStart: 15,
    inventoryAdded: null,
    weekEnd: 10,
    order: 5,
    amount: null,
    boxes: 10,
  },
  {
    itemName: "Non-Dairy Creamer (20/box)",
    weekStart: 42,
    inventoryAdded: 80,
    weekEnd: 53,
    order: 69,
    amount: null,
    boxes: 20,
  },
  {
    itemName: "Instant Q Jelly Powder (10/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 10,
  },
  {
    itemName: "Black Sesame (8/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 8,
  },
  {
    itemName: "Grapefruit Syrup (4/box)",
    weekStart: 3,
    inventoryAdded: 4,
    weekEnd: 4,
    order: 3,
    amount: null,
    boxes: 4,
  },
  {
    itemName: "Passionfruit Syrup (4/box)",
    weekStart: 5,
    inventoryAdded: 4,
    weekEnd: 6,
    order: 3,
    amount: null,
    boxes: 4,
  },
  {
    itemName: "Mango Syrup (4/box)",
    weekStart: 4,
    inventoryAdded: 12,
    weekEnd: 8,
    order: 8,
    amount: null,
    boxes: 4,
  },
  {
    itemName: "Black Sugar (box)",
    weekStart: 5,
    inventoryAdded: 5,
    weekEnd: 5,
    order: 5,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Wintermelon Bricks (20/box)",
    weekStart: 14,
    inventoryAdded: 20,
    weekEnd: 22,
    order: 12,
    amount: null,
    boxes: 20,
  },
  {
    itemName: "White Peach Oolong Tea (30/box)",
    weekStart: 30,
    inventoryAdded: null,
    weekEnd: 30,
    order: 0,
    amount: null,
    boxes: 30,
  },
  {
    itemName: "Ceylon Black Tea (96/box)",
    weekStart: 1,
    inventoryAdded: 1,
    weekEnd: 1,
    order: 1,
    amount: null,
    boxes: 96,
  },
  {
    itemName: "Jasmine Tea (108/box)",
    weekStart: 1.25,
    inventoryAdded: 1,
    weekEnd: 1.2,
    order: 1.05,
    amount: null,
    boxes: 108,
  },
  {
    itemName: "Roasted Oolong Tea (108/box)",
    weekStart: 0.8,
    inventoryAdded: 1,
    weekEnd: 1.3,
    order: 0.5,
    amount: null,
    boxes: 108,
  },
  {
    itemName: "Four Seasons Tea (142/box)",
    weekStart: 0.9,
    inventoryAdded: 1,
    weekEnd: 2,
    order: -0.1,
    amount: null,
    boxes: 142,
  },
  {
    itemName: "Thai Tea (30/box)",
    weekStart: 7,
    inventoryAdded: 30,
    weekEnd: 25,
    order: 12,
    amount: null,
    boxes: 30,
  },
  {
    itemName: "Honey Syrup (6/box)",
    weekStart: 13,
    inventoryAdded: 12,
    weekEnd: 18,
    order: 7,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Grass Jelly Can (6/box) – Herb Juice",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Red Bean (18/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 18,
  },
  {
    itemName: "Condensed Milk (Large) 6/box",
    weekStart: 14,
    inventoryAdded: 18,
    weekEnd: 17,
    order: 15,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Condensed Milk (Small) 24/box",
    weekStart: 34,
    inventoryAdded: 24,
    weekEnd: 34,
    order: 24,
    amount: null,
    boxes: 24,
  },
  {
    itemName: "Liquid Cane Sugar (4/box)",
    weekStart: 39,
    inventoryAdded: 32,
    weekEnd: 37,
    order: 34,
    amount: null,
    boxes: 4,
  },
  {
    itemName: "Agar Boba (6/box)",
    weekStart: 16,
    inventoryAdded: 12,
    weekEnd: 11,
    order: 17,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Lychee Jelly (4/box)",
    weekStart: 12,
    inventoryAdded: 12,
    weekEnd: 9,
    order: 15,
    amount: null,
    boxes: 4,
  },
  {
    itemName: "Cups – 700 ml",
    weekStart: 12,
    inventoryAdded: 12,
    weekEnd: 10,
    order: 14,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Cups – 500 ml",
    weekStart: 1,
    inventoryAdded: 1,
    weekEnd: 2,
    order: 0,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Cup Lids",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    order: "#VALUE!",
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Karat Paperboard w/Handle",
    weekStart: 1,
    inventoryAdded: null,
    weekEnd: 2,
    order: -1,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "PE Clear 4-Cup Bags",
    weekStart: 1,
    inventoryAdded: null,
    weekEnd: 1,
    order: 0,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Karat 4-Cup Holder",
    weekStart: 1,
    inventoryAdded: 2,
    weekEnd: 2,
    order: 1,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Large Order Box (25/pack)",
    weekStart: null,
    inventoryAdded: 25,
    weekEnd: 22,
    order: 3,
    amount: null,
    boxes: 25,
  },
  {
    itemName: "2 oz Sample Cups",
    weekStart: null,
    inventoryAdded: 1,
    weekEnd: null,
    order: 1,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Straws – Large",
    weekStart: 6,
    inventoryAdded: null,
    weekEnd: 2,
    order: 4,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Straws – Small",
    weekStart: 1,
    inventoryAdded: 1,
    weekEnd: 1,
    order: 1,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Togo Bag – 4 Drinks",
    weekStart: 2,
    inventoryAdded: 1,
    weekEnd: 2,
    order: 1,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Togo Bag – 2 Drinks",
    weekStart: 1,
    inventoryAdded: 1,
    weekEnd: 2,
    order: 0,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Seal Roll (6/box)",
    weekStart: 6,
    inventoryAdded: null,
    weekEnd: 4,
    order: 2,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Hokkaido Powder (20/box)",
    weekStart: 30,
    inventoryAdded: null,
    weekEnd: 20,
    order: 10,
    amount: null,
    boxes: 20,
  },
  {
    itemName: "Matcha Powder (10/box)",
    weekStart: 4,
    inventoryAdded: 10,
    weekEnd: 8,
    order: 6,
    amount: null,
    boxes: 10,
  },
  {
    itemName: "Chocolate Powder (20 bags)",
    weekStart: 10,
    inventoryAdded: 20,
    weekEnd: 25,
    order: 5,
    amount: null,
    boxes: 20,
  },
  {
    itemName: "Orange",
    weekStart: 1,
    inventoryAdded: 2,
    weekEnd: 2,
    order: 1,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Lemon",
    weekStart: 2,
    inventoryAdded: 1,
    weekEnd: 0.5,
    order: 2.5,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Grapefruit",
    weekStart: 2,
    inventoryAdded: 3,
    weekEnd: 2.5,
    order: 2.5,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Fresh Strawberry",
    weekStart: 11,
    inventoryAdded: 8,
    weekEnd: 6,
    order: 13,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Mango",
    weekStart: 4,
    inventoryAdded: 20,
    weekEnd: 7,
    order: 17,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Yakult",
    weekStart: 12,
    inventoryAdded: 10,
    weekEnd: 10,
    order: 12,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Receipt Paper",
    weekStart: 11,
    inventoryAdded: null,
    weekEnd: 9,
    order: 2,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Label Paper (32/box)",
    weekStart: 7,
    inventoryAdded: 32,
    weekEnd: 28,
    order: 11,
    amount: null,
    boxes: 32,
  },
  {
    itemName: "Whole Milk (2/box)",
    weekStart: 34,
    inventoryAdded: 90,
    weekEnd: 64,
    order: 60,
    amount: null,
    boxes: 2,
  },
  {
    itemName: "Heavy Cream (6/box)",
    weekStart: 3,
    inventoryAdded: 36,
    weekEnd: 6,
    order: 33,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "White Sugar (25 lb units)",
    weekStart: null,
    inventoryAdded: 1,
    weekEnd: "good",
    order: "#VALUE!",
    amount: null,
    boxes: 25,
  },
  {
    itemName: "Evaporated Milk (12/box)",
    weekStart: 9,
    inventoryAdded: 36,
    weekEnd: 10,
    order: 35,
    amount: null,
    boxes: 12,
  },
  {
    itemName: "Strawberry Jam (2/pack)",
    weekStart: 2,
    inventoryAdded: 4,
    weekEnd: 0,
    order: 6,
    amount: null,
    boxes: 2,
  },
  {
    itemName: "Caramel Sauce",
    weekStart: 1,
    inventoryAdded: 2,
    weekEnd: 2,
    order: 1,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Sea Salt",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    order: "#VALUE!",
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Imitation Vanilla Extract",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    order: "#VALUE!",
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Organic Milk (3/box)",
    weekStart: 9,
    inventoryAdded: 18,
    weekEnd: 18,
    order: 9,
    amount: null,
    boxes: 3,
  },
  {
    itemName: "Cream Cheese",
    weekStart: 4,
    inventoryAdded: 4,
    weekEnd: 3,
    order: 5,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Almond Milk (6/box)",
    weekStart: 25,
    inventoryAdded: 30,
    weekEnd: 30,
    order: 25,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Oat Milk (6/box)",
    weekStart: 36,
    inventoryAdded: 66,
    weekEnd: 24,
    order: 78,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Oreo Cookies",
    weekStart: 8,
    inventoryAdded: 7,
    weekEnd: 6,
    order: 9,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Dried Mango Slices",
    weekStart: 3,
    inventoryAdded: 4,
    weekEnd: 2,
    order: 5,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Napkin (4-bundle pack)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: 0.5,
    order: -0.5,
    amount: null,
    boxes: 4,
  },
  {
    itemName: "Trash Bag – White",
    weekStart: 2,
    inventoryAdded: null,
    weekEnd: 1,
    order: 1,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Trash Bag – Black",
    weekStart: 2,
    inventoryAdded: null,
    weekEnd: 1,
    order: 1,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Masking Tape (Yellow, 6/pack)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Packaging Tape (Clear, 6/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "White Rags",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    order: "#VALUE!",
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Yellow Rags",
    weekStart: 2,
    inventoryAdded: null,
    weekEnd: "good",
    order: "#VALUE!",
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Dish Soap",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: 2,
    order: -2,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Sponges",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    order: "#VALUE!",
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Bleach (3/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: 1,
    order: -1,
    amount: null,
    boxes: 3,
  },
  {
    itemName: "Pine-Sol / Fabuloso",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    order: "#VALUE!",
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Comet / Ajax (6/pack)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    order: "#VALUE!",
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Styrofoam Cups",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    order: "#VALUE!",
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Gloves",
    weekStart: null,
    inventoryAdded: "4/4/0",
    weekEnd: -36620,
    order: "0/0/2",
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Masks",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    order: "#VALUE!",
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Sanitizer",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    order: "#VALUE!",
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Toilet Paper",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    order: "#VALUE!",
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Paper Towel (12 ct)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    order: "#VALUE!",
    amount: null,
    boxes: 12,
  },
  {
    itemName: "Hand Soap (4/pack)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    order: "#VALUE!",
    amount: null,
    boxes: 4,
  },
  {
    itemName: "Biscoff Cookies – Costco",
    weekStart: null,
    inventoryAdded: 6,
    weekEnd: 0,
    order: 6,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Kataifi",
    weekStart: null,
    inventoryAdded: 5,
    weekEnd: 3,
    order: 2,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Tajin (2 ct)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: 3,
    order: -3,
    amount: null,
    boxes: 2,
  },
  {
    itemName: "Chamoy (big/small)",
    weekStart: 5,
    inventoryAdded: null,
    weekEnd: 4,
    order: 1,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Lemon Juice (2/pack)",
    weekStart: 3,
    inventoryAdded: 4,
    weekEnd: 2,
    order: 5,
    amount: null,
    boxes: 2,
  },
  {
    itemName: "Toilet Seat Cover",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    order: "#VALUE!",
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Mop Head",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    order: "#VALUE!",
    amount: null,
    boxes: 1,
  },
];
const inventoryEmpty = [
  {
    itemName: "Boba-Brown (6/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Boba-White (6/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Cream Pudding Powder (20/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 20,
  },
  {
    itemName: "Mochi Powder (20/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 20,
  },
  {
    itemName: "Cheese Foam Powder (20/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 20,
  },
  {
    itemName: "Pudding Powder (20/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 20,
  },
  {
    itemName: "Casava/Starch Powder (20/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 20,
  },
  {
    itemName: "Plain Jelly Powder (10/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 10,
  },
  {
    itemName: "Non-Dairy Creamer (20/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 20,
  },
  {
    itemName: "Instant Q Jelly Powder (10/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 10,
  },
  {
    itemName: "Black Sesame (8/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 8,
  },
  {
    itemName: "Grapefruit Syrup (4/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 4,
  },
  {
    itemName: "Passionfruit Syrup (4/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 4,
  },
  {
    itemName: "Mango Syrup (4/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 4,
  },
  {
    itemName: "Black Sugar (box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Wintermelon Bricks (20/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 20,
  },
  {
    itemName: "White Peach Oolong Tea (30/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 30,
  },
  {
    itemName: "Ceylon Black Tea (96/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 96,
  },
  {
    itemName: "Jasmine Tea (108/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 108,
  },
  {
    itemName: "Roasted Oolong Tea (108/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 108,
  },
  {
    itemName: "Four Seasons Tea (142/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 142,
  },
  {
    itemName: "Thai Tea (30/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 30,
  },
  {
    itemName: "Honey Syrup (6/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Grass Jelly Can (6/box) – Herb Juice",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Red Bean (18/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 18,
  },
  {
    itemName: "Condensed Milk (Large) 6/box",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Condensed Milk (Small) 24/box",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 24,
  },
  {
    itemName: "Liquid Cane Sugar (4/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 4,
  },
  {
    itemName: "Agar Boba (6/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Lychee Jelly (4/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 4,
  },
  {
    itemName: "Cups – 700 ml",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Cups – 500 ml",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Cup Lids",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Karat Paperboard w/Handle",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "PE Clear 4-Cup Bags",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Karat 4-Cup Holder",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Large Order Box (25/pack)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 25,
  },
  {
    itemName: "2 oz Sample Cups",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Straws – Large",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Straws – Small",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Togo Bag – 4 Drinks",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Togo Bag – 2 Drinks",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Seal Roll (6/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Hokkaido Powder (20/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 20,
  },
  {
    itemName: "Matcha Powder (10/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 10,
  },
  {
    itemName: "Chocolate Powder (20 bags)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 20,
  },
  {
    itemName: "Orange",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Lemon",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Grapefruit",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Fresh Strawberry",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Mango",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Yakult",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Receipt Paper",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Label Paper (32/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 32,
  },
  {
    itemName: "Whole Milk (2/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 2,
  },
  {
    itemName: "Heavy Cream (6/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "White Sugar (25 lb units)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 25,
  },
  {
    itemName: "Evaporated Milk (12/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 12,
  },
  {
    itemName: "Strawberry Jam (2/pack)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 2,
  },
  {
    itemName: "Caramel Sauce",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Sea Salt",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Imitation Vanilla Extract",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Organic Milk (3/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 3,
  },
  {
    itemName: "Cream Cheese",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Almond Milk (6/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Oat Milk (6/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Oreo Cookies",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Dried Mango Slices",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Napkin (4-bundle pack)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 4,
  },
  {
    itemName: "Trash Bag – White",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Trash Bag – Black",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Masking Tape (Yellow, 6/pack)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Packaging Tape (Clear, 6/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "White Rags",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Yellow Rags",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Dish Soap",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Sponges",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Bleach (3/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 3,
  },
  {
    itemName: "Pine-Sol / Fabuloso",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Comet / Ajax (6/pack)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 6,
  },
  {
    itemName: "Styrofoam Cups",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Gloves",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Masks",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Sanitizer",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Toilet Paper",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Paper Towel (12 ct)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 12,
  },
  {
    itemName: "Hand Soap (4/pack)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 4,
  },
  {
    itemName: "Biscoff Cookies – Costco",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Kataifi",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Tajin (2 ct)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 2,
  },
  {
    itemName: "Chamoy (big/small)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Lemon Juice (2/pack)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 2,
  },
  {
    itemName: "Toilet Seat Cover",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
  {
    itemName: "Mop Head",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    order: null,
    amount: null,
    boxes: 1,
  },
];

interface TestDataInterface {
  [key: string]: any[];
}

function Inventory() {
  const [selectedDate, setSelectedDate] = useState(() => {
    const now = dayjs();
    const nowNumber = now.day();
    const changeToCorrect = now.subtract(nowNumber, "day");
    return changeToCorrect;
  });
  const [colData, setColData] = useState([
    {
      field: "itemName",
      flex: 2.5,
      cellClass: "highlight-column",
      mode: "singleRow",
      checkboxes: false,
      enableClickSelection: true,
    },
    { field: "weekStart", headerName: "Week Start", flex: 1, editable: true },
    {
      field: "inventoryAdded",
      headerName: "InventoryAdded",
      editable: true,
      flex: 1,
    },
    { field: "weekEnd", headerName: "Week End", flex: 1, editable: true },
    {
      field: "usage",
      headerName: "Usage",
      flex: 1,
      valueGetter: usageGetter,
    },
    {
      field: "order",
      headerName: "Order (by Box)",
      flex: 1,
      editable: true,

      // ⇢ Runs every time any cell in the row changes
      valueGetter: (params) => {
        if (params.data.order) return params.data.order; // user override

        // same logic you already wrote
        const usage = usageGetter(params);
        const { weekEnd, boxes } = params.data;

        if (typeof weekEnd === "string" || weekEnd == null) return "N/A";

        const calc = Math.round((usage * 2 - weekEnd) / boxes);
        return calc < 0 ? "N/A" : calc;
      },

      // ⇢ Purely cosmetic renderer
      cellRenderer: (params) =>
        params.data.order ?? ( // real order entered?
          <span className="light-color">Suggested: {params.value}</span>
        ),
    },
    { field: "amount", headerName: "Amount By Delivery" },
    {
      field: "boxes",
      hide: true,
    },
  ]);

  const [testData, setTestData] = useState<TestDataInterface>({});
  const [rowData, setRowData] = useState(inventoryEmpty);
  useEffect(() => {
    testData[selectedDate.format("YYYY-MM-DD")] = inventoryEmpty;
    console.log(
      testData,
      "UseEffect Test Data, make sure it runs when page renders"
    );
  }, []);
  function DatePickerOnlySunday() {
    return (
      <LocalizationProvider dateAdapter={AdapterDayjs}>
        <DatePicker
          label="My date picker"
          shouldDisableDate={(date: any) => {
            return date.day() != 0;
          }}
          format="MM/DD/YYYY"
          disablePast={false}
          value={selectedDate}
          onChange={onChangeDate}
        />
      </LocalizationProvider>
    );
  }
  function onChangeDate(params) {
    if (!params) return;

    const testDate = dayjs(params);
    const testDateString = testDate.format("YYYY-MM-DD");

    setSelectedDate(testDate);

    if (testDateString in testData) {
      setRowData(testData[testDateString]);
    } else {
      setTestData((prev) => ({
        ...prev,
        [testDateString]: [...inventoryEmpty],
      }));
      setRowData([...inventoryEmpty]);
    }
  }

  function onGridChange(params) {
    const dateKey = selectedDate.format("YYYY-MM-DD");
    const currentRowChangedName = params.data;
    const newData = [...testData[dateKey]];
    newData[params.rowIndex] = currentRowChangedName;

    setTestData((prev) => ({
      ...prev,
      [dateKey]: newData,
    }));
    setRowData(newData);
  }

  function usageGetter(params) {
    const weekStart = params.data.weekStart || 0;
    const inventoryAdded = params.data.inventoryAdded || 0;
    const weekEnd = params.data.weekEnd;

    if (weekEnd === "good" || weekEnd === null) {
      return 0;
    }

    return weekStart + inventoryAdded - weekEnd;
  }

  const defaultColDef = useMemo(() => {
    return {
      cellEditor: "agNumberCellEditor",
      cellEditorParams: {
        preventStepping: true,
      },
      rowSelection: {
        mode: "multiRow",
        checkboxes: false,
        headerCheckbox: false,
        enableClickSelection: true,
      },
      cellClass: "other-rows",
    };
  }, []);
  return (
    <>
      <button>take from previous week</button>
      <button>Reset Inventory</button>
      <button>Reset Week</button>
      <div className="box" id="date">
        <h3>Date</h3>
        <DatePickerOnlySunday />
      </div>
      <div className="graph-container">
        <div className="meow ag-theme-alpine">
          <AgGridReact
            rowData={rowData}
            columnDefs={colData}
            enterNavigatesVerticallyAfterEdit={true}
            defaultColDef={defaultColDef}
            rowSelection="multiple"
            onCellValueChanged={onGridChange}
          />
        </div>
      </div>
    </>
  );
}

export default Inventory;
