import { AgGridReact } from "ag-grid-react";
import { useState } from "react";
import "ag-grid-community/styles/ag-grid.css";
import "ag-grid-community/styles/ag-theme-alpine.css";
import { ModuleRegistry, AllCommunityModule } from "ag-grid-community";

ModuleRegistry.registerModules([AllCommunityModule]);
const inventoryRows = [
  {
    itemName: "Boba-Brown (6/box)",
    weekStart: 43,
    inventoryAdded: 42,
    weekEnd: 44,
    usage: 41,
    order: 8,
    amount: null,
  },
  {
    itemName: "Boba-White (6/box)",
    weekStart: 21,
    inventoryAdded: 18,
    weekEnd: 25,
    usage: 14,
    order: 3,
    amount: null,
  },
  {
    itemName: "Cream Pudding Powder (20/box)",
    weekStart: 15,
    inventoryAdded: null,
    weekEnd: 10,
    usage: 5,
    order: 1,
    amount: null,
  },
  {
    itemName: "Mochi Powder (20/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    usage: null,
    order: 0,
    amount: null,
  },
  {
    itemName: "Cheese Foam Powder (20/box)",
    weekStart: 12,
    inventoryAdded: 20,
    weekEnd: 32,
    usage: 0,
    order: null,
    amount: null,
  },
  {
    itemName: "Pudding Powder (20/box)",
    weekStart: 35,
    inventoryAdded: null,
    weekEnd: 29,
    usage: 6,
    order: null,
    amount: null,
  },
  {
    itemName: "Casava/Starch Powder (20/box)",
    weekStart: 20,
    inventoryAdded: null,
    weekEnd: 20,
    usage: 0,
    order: null,
    amount: null,
  },
  {
    itemName: "Plain Jelly Powder (10/box)",
    weekStart: 15,
    inventoryAdded: null,
    weekEnd: 10,
    usage: 5,
    order: 1,
    amount: null,
  },
  {
    itemName: "Non-Dairy Creamer (20/box)",
    weekStart: 42,
    inventoryAdded: 80,
    weekEnd: 53,
    usage: 69,
    order: 4,
    amount: null,
  },
  {
    itemName: "Instant Q Jelly Powder (10/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    usage: null,
    order: 0,
    amount: null,
  },
  {
    itemName: "Black Sesame (8/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    usage: null,
    order: 0,
    amount: null,
  },
  {
    itemName: "Grapefruit Syrup (4/box)",
    weekStart: 3,
    inventoryAdded: 4,
    weekEnd: 4,
    usage: 3,
    order: 1,
    amount: null,
  },
  {
    itemName: "Passionfruit Syrup (4/box)",
    weekStart: 5,
    inventoryAdded: 4,
    weekEnd: 6,
    usage: 3,
    order: 1,
    amount: null,
  },
  {
    itemName: "Mango Syrup (4/box)",
    weekStart: 4,
    inventoryAdded: 12,
    weekEnd: 8,
    usage: 8,
    order: 2,
    amount: null,
  },
  {
    itemName: "Black Sugar (box)",
    weekStart: 5,
    inventoryAdded: 5,
    weekEnd: 5,
    usage: 5,
    order: 5,
    amount: null,
  },
  {
    itemName: "Wintermelon Bricks (20/box)",
    weekStart: 14,
    inventoryAdded: 20,
    weekEnd: 22,
    usage: 12,
    order: 1,
    amount: null,
  },
  {
    itemName: "White Peach Oolong Tea (30/box)",
    weekStart: 30,
    inventoryAdded: null,
    weekEnd: 30,
    usage: 0,
    order: null,
    amount: null,
  },
  {
    itemName: "Ceylon Black Tea (96/box)",
    weekStart: 1,
    inventoryAdded: 1,
    weekEnd: 1,
    usage: 1,
    order: 1,
    amount: null,
  },
  {
    itemName: "Jasmine Tea (108/box)",
    weekStart: 1.25,
    inventoryAdded: 1,
    weekEnd: 1.2,
    usage: 1.05,
    order: 1,
    amount: null,
  },
  {
    itemName: "Roasted Oolong Tea (108/box)",
    weekStart: 0.8,
    inventoryAdded: 1,
    weekEnd: 1.3,
    usage: 0.5,
    order: null,
    amount: null,
  },
  {
    itemName: "Four Seasons Tea (142/box)",
    weekStart: 0.9,
    inventoryAdded: 1,
    weekEnd: 2,
    usage: -0.1,
    order: null,
    amount: null,
  },
  {
    itemName: "Thai Tea (30/box)",
    weekStart: 7,
    inventoryAdded: 30,
    weekEnd: 25,
    usage: 12,
    order: 1,
    amount: null,
  },
  {
    itemName: "Honey Syrup (6/box)",
    weekStart: 13,
    inventoryAdded: 12,
    weekEnd: 18,
    usage: 7,
    order: null,
    amount: null,
  },
  {
    itemName: "Grass Jelly Can (6/box) – Herb Juice",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    usage: null,
    order: 0,
    amount: null,
  },
  {
    itemName: "Red Bean (18/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    usage: null,
    order: 0,
    amount: null,
  },
  {
    itemName: "Condensed Milk (Large) 6/box",
    weekStart: 14,
    inventoryAdded: 18,
    weekEnd: 17,
    usage: 15,
    order: 3,
    amount: null,
  },
  {
    itemName: "Condensed Milk (Small) 24/box",
    weekStart: 34,
    inventoryAdded: 24,
    weekEnd: 34,
    usage: 24,
    order: 1,
    amount: null,
  },
  {
    itemName: "Liquid Cane Sugar (4/box)",
    weekStart: 39,
    inventoryAdded: 32,
    weekEnd: 37,
    usage: 34,
    order: 8,
    amount: null,
  },
  {
    itemName: "Agar Boba (6/box)",
    weekStart: 16,
    inventoryAdded: 12,
    weekEnd: 11,
    usage: 17,
    order: 3,
    amount: null,
  },
  {
    itemName: "Lychee Jelly (4/box)",
    weekStart: 12,
    inventoryAdded: 12,
    weekEnd: 9,
    usage: 15,
    order: 4,
    amount: null,
  },
  {
    itemName: "Cups – 700 ml",
    weekStart: 12,
    inventoryAdded: 12,
    weekEnd: 10,
    usage: 14,
    order: 13,
    amount: null,
  },
  {
    itemName: "Cups – 500 ml",
    weekStart: 1,
    inventoryAdded: 1,
    weekEnd: 2,
    usage: 0,
    order: 2,
    amount: null,
  },
  {
    itemName: "Cup Lids",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    usage: "#VALUE!",
    order: null,
    amount: null,
  },
  {
    itemName: "Karat Paperboard w/Handle",
    weekStart: 1,
    inventoryAdded: null,
    weekEnd: 2,
    usage: -1,
    order: null,
    amount: null,
  },
  {
    itemName: "PE Clear 4-Cup Bags",
    weekStart: 1,
    inventoryAdded: null,
    weekEnd: 1,
    usage: 0,
    order: null,
    amount: null,
  },
  {
    itemName: "Karat 4-Cup Holder",
    weekStart: 1,
    inventoryAdded: 2,
    weekEnd: 2,
    usage: 1,
    order: 1,
    amount: null,
  },
  {
    itemName: "Large Order Box (25/pack)",
    weekStart: null,
    inventoryAdded: 25,
    weekEnd: 22,
    usage: 3,
    order: null,
    amount: null,
  },
  {
    itemName: "2 oz Sample Cups",
    weekStart: null,
    inventoryAdded: 1,
    weekEnd: null,
    usage: 1,
    order: null,
    amount: null,
  },
  {
    itemName: "Straws – Large",
    weekStart: 6,
    inventoryAdded: null,
    weekEnd: 2,
    usage: 4,
    order: 4,
    amount: null,
  },
  {
    itemName: "Straws – Small",
    weekStart: 1,
    inventoryAdded: 1,
    weekEnd: 1,
    usage: 1,
    order: 1,
    amount: null,
  },
  {
    itemName: "Togo Bag – 4 Drinks",
    weekStart: 2,
    inventoryAdded: 1,
    weekEnd: 2,
    usage: 1,
    order: 1,
    amount: null,
  },
  {
    itemName: "Togo Bag – 2 Drinks",
    weekStart: 1,
    inventoryAdded: 1,
    weekEnd: 2,
    usage: 0,
    order: null,
    amount: null,
  },
  {
    itemName: "Seal Roll (6/box)",
    weekStart: 6,
    inventoryAdded: null,
    weekEnd: 4,
    usage: 2,
    order: null,
    amount: null,
  },
  {
    itemName: "Hokkaido Powder (20/box)",
    weekStart: 30,
    inventoryAdded: null,
    weekEnd: 20,
    usage: 10,
    order: null,
    amount: null,
  },
  {
    itemName: "Matcha Powder (10/box)",
    weekStart: 4,
    inventoryAdded: 10,
    weekEnd: 8,
    usage: 6,
    order: null,
    amount: null,
  },
  {
    itemName: "Chocolate Powder (20 bags)",
    weekStart: 10,
    inventoryAdded: 20,
    weekEnd: 25,
    usage: 5,
    order: null,
    amount: null,
  },
  {
    itemName: "Orange",
    weekStart: 1,
    inventoryAdded: 2,
    weekEnd: 2,
    usage: 1,
    order: 2,
    amount: null,
  },
  {
    itemName: "Lemon",
    weekStart: 2,
    inventoryAdded: 1,
    weekEnd: 0.5,
    usage: 2.5,
    order: 1,
    amount: null,
  },
  {
    itemName: "Grapefruit",
    weekStart: 2,
    inventoryAdded: 3,
    weekEnd: 2.5,
    usage: 2.5,
    order: 3,
    amount: null,
  },
  {
    itemName: "Fresh Strawberry",
    weekStart: 11,
    inventoryAdded: 8,
    weekEnd: 6,
    usage: 13,
    order: 15,
    amount: null,
  },
  {
    itemName: "Mango",
    weekStart: 4,
    inventoryAdded: 20,
    weekEnd: 7,
    usage: 17,
    order: 16,
    amount: null,
  },
  {
    itemName: "Yakult",
    weekStart: 12,
    inventoryAdded: 10,
    weekEnd: 10,
    usage: 12,
    order: 12,
    amount: null,
  },
  {
    itemName: "Receipt Paper",
    weekStart: 11,
    inventoryAdded: null,
    weekEnd: 9,
    usage: 2,
    order: null,
    amount: null,
  },
  {
    itemName: "Label Paper (32/box)",
    weekStart: 7,
    inventoryAdded: 32,
    weekEnd: 28,
    usage: 11,
    order: null,
    amount: null,
  },
  {
    itemName: "Whole Milk (2/box)",
    weekStart: 34,
    inventoryAdded: 90,
    weekEnd: 64,
    usage: 60,
    order: 30,
    amount: null,
  },
  {
    itemName: "Heavy Cream (6/box)",
    weekStart: 3,
    inventoryAdded: 36,
    weekEnd: 6,
    usage: 33,
    order: 36,
    amount: null,
  },
  {
    itemName: "White Sugar (25 lb units)",
    weekStart: null,
    inventoryAdded: 1,
    weekEnd: "good",
    usage: "#VALUE!",
    order: null,
    amount: null,
  },
  {
    itemName: "Evaporated Milk (12/box)",
    weekStart: 9,
    inventoryAdded: 36,
    weekEnd: 10,
    usage: 35,
    order: 3,
    amount: null,
  },
  {
    itemName: "Strawberry Jam (2/pack)",
    weekStart: 2,
    inventoryAdded: 4,
    weekEnd: 0,
    usage: 6,
    order: 3,
    amount: null,
  },
  {
    itemName: "Caramel Sauce",
    weekStart: 1,
    inventoryAdded: 2,
    weekEnd: 2,
    usage: 1,
    order: 1,
    amount: null,
  },
  {
    itemName: "Sea Salt",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    usage: "#VALUE!",
    order: null,
    amount: null,
  },
  {
    itemName: "Imitation Vanilla Extract",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    usage: "#VALUE!",
    order: null,
    amount: null,
  },
  {
    itemName: "Organic Milk (3/box)",
    weekStart: 9,
    inventoryAdded: 18,
    weekEnd: 18,
    usage: 9,
    order: 3,
    amount: null,
  },
  {
    itemName: "Cream Cheese",
    weekStart: 4,
    inventoryAdded: 4,
    weekEnd: 3,
    usage: 5,
    order: 5,
    amount: null,
  },
  {
    itemName: "Almond Milk (6/box)",
    weekStart: 25,
    inventoryAdded: 30,
    weekEnd: 30,
    usage: 25,
    order: 4,
    amount: null,
  },
  {
    itemName: "Oat Milk (6/box)",
    weekStart: 36,
    inventoryAdded: 66,
    weekEnd: 24,
    usage: 78,
    order: 13,
    amount: null,
  },
  {
    itemName: "Oreo Cookies",
    weekStart: 8,
    inventoryAdded: 7,
    weekEnd: 6,
    usage: 9,
    order: 9,
    amount: null,
  },
  {
    itemName: "Dried Mango Slices",
    weekStart: 3,
    inventoryAdded: 4,
    weekEnd: 2,
    usage: 5,
    order: 5,
    amount: null,
  },
  {
    itemName: "Napkin (4-bundle pack)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: 0.5,
    usage: -0.5,
    order: 1,
    amount: null,
  },
  {
    itemName: "Trash Bag – White",
    weekStart: 2,
    inventoryAdded: null,
    weekEnd: 1,
    usage: 1,
    order: 1,
    amount: null,
  },
  {
    itemName: "Trash Bag – Black",
    weekStart: 2,
    inventoryAdded: null,
    weekEnd: 1,
    usage: 1,
    order: 1,
    amount: null,
  },
  {
    itemName: "Masking Tape (Yellow, 6/pack)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    usage: null,
    order: 0,
    amount: null,
  },
  {
    itemName: "Packaging Tape (Clear, 6/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: null,
    usage: null,
    order: 0,
    amount: null,
  },
  {
    itemName: "White Rags",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    usage: "#VALUE!",
    order: null,
    amount: null,
  },
  {
    itemName: "Yellow Rags",
    weekStart: 2,
    inventoryAdded: null,
    weekEnd: "good",
    usage: "#VALUE!",
    order: null,
    amount: null,
  },
  {
    itemName: "Dish Soap",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: 2,
    usage: -2,
    order: null,
    amount: null,
  },
  {
    itemName: "Sponges",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    usage: "#VALUE!",
    order: null,
    amount: null,
  },
  {
    itemName: "Bleach (3/box)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: 1,
    usage: -1,
    order: 1,
    amount: null,
  },
  {
    itemName: "Pine-Sol / Fabuloso",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    usage: "#VALUE!",
    order: null,
    amount: null,
  },
  {
    itemName: "Comet / Ajax (6/pack)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    usage: "#VALUE!",
    order: null,
    amount: null,
  },
  {
    itemName: "Styrofoam Cups",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    usage: "#VALUE!",
    order: null,
    amount: null,
  },
  {
    itemName: "Gloves",
    weekStart: null,
    inventoryAdded: "4/4/0",
    weekEnd: -36620,
    usage: "0/0/2",
    order: null,
    amount: null,
  },
  {
    itemName: "Masks",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    usage: "#VALUE!",
    order: null,
    amount: null,
  },
  {
    itemName: "Sanitizer",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    usage: "#VALUE!",
    order: null,
    amount: null,
  },
  {
    itemName: "Toilet Paper",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    usage: "#VALUE!",
    order: null,
    amount: null,
  },
  {
    itemName: "Paper Towel (12 ct)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    usage: "#VALUE!",
    order: null,
    amount: null,
  },
  {
    itemName: "Hand Soap (4/pack)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    usage: "#VALUE!",
    order: null,
    amount: null,
  },
  {
    itemName: "Biscoff Cookies – Costco",
    weekStart: null,
    inventoryAdded: 6,
    weekEnd: 0,
    usage: 6,
    order: 20,
    amount: null,
  },
  {
    itemName: "Kataifi",
    weekStart: null,
    inventoryAdded: 5,
    weekEnd: 3,
    usage: 2,
    order: 3,
    amount: null,
  },
  {
    itemName: "Tajin (2 ct)",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: 3,
    usage: -3,
    order: null,
    amount: null,
  },
  {
    itemName: "Chamoy (big/small)",
    weekStart: 5,
    inventoryAdded: null,
    weekEnd: 4,
    usage: 1,
    order: null,
    amount: null,
  },
  {
    itemName: "Lemon Juice (2/pack)",
    weekStart: 3,
    inventoryAdded: 4,
    weekEnd: 2,
    usage: 5,
    order: 2,
    amount: null,
  },
  {
    itemName: "Toilet Seat Cover",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    usage: "#VALUE!",
    order: null,
    amount: null,
  },
  {
    itemName: "Mop Head",
    weekStart: null,
    inventoryAdded: null,
    weekEnd: "good",
    usage: "#VALUE!",
    order: null,
    amount: null,
  },
];
function Inventory() {
  const [colData, setColData] = useState([
    { field: "itemName" },
    { field: "weekStart", headerName: "Week Start" },
    { field: "inventoryAdded", headerName: "InventoryAdded" },
    { field: "weekEnd", headerName: "Week End" },
    { field: "usage", headerName: "Usage" },
    { field: "order", headerName: "Order (by Box)" },
    { field: "amount", headerName: "Amount By Delivery" },
  ]);

  const [rowData, setRowData] = useState(inventoryRows);

  return (
    <>
      <div
        className="meow ag-theme-alpine"
        style={{ height: "100vh", width: "100%" }}
      >
        <AgGridReact rowData={rowData} columnDefs={colData} />
      </div>
    </>
  );
}

export default Inventory;
