name: Deploy to GitHub Pages with Docker

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: builder
          tags: nuxt-app:builder
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Pass build args if needed for Firebase/Analytics
          build-args: |
            API_KEY=${{ secrets.API_KEY }}
            AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }}
            PROJECT_ID=${{ secrets.PROJECT_ID }}
            STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }}
            MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }}
            APP_ID=${{ secrets.APP_ID }}
            MEASUREMENT_ID=${{ secrets.MEASUREMENT_ID }}

      - name: Create container and copy static files
        run: |
          # Create a container from the builder image
          docker create --name temp-container nuxt-app:builder

          # Create directory to store static files
          mkdir -p ./dist

          # Copy static files from container to host
          docker cp temp-container:/app/dist ./dist/

          # Clean up container
          docker rm temp-container

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
