name: Deploy to GitHub Pages with Docker

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image and extract static files
        run: |
          # Build the Docker image
          docker build --target builder \
            --build-arg API_KEY="${{ secrets.API_KEY }}" \
            --build-arg AUTH_DOMAIN="${{ secrets.AUTH_DOMAIN }}" \
            --build-arg PROJECT_ID="${{ secrets.PROJECT_ID }}" \
            --build-arg STORAGE_BUCKET="${{ secrets.STORAGE_BUCKET }}" \
            --build-arg MESSAGING_SENDER_ID="${{ secrets.MESSAGING_SENDER_ID }}" \
            --build-arg APP_ID="${{ secrets.APP_ID }}" \
            --build-arg MEASUREMENT_ID="${{ secrets.MEASUREMENT_ID }}" \
            -t nuxt-builder .

          # Create a container from the builder image
          docker create --name temp-container nuxt-builder

          # Create directory to store static files
          mkdir -p ./dist

          # Copy static files from container to host (contents only)
          docker cp temp-container:/app/dist/. ./dist/

      - name: Create 404.html for GitHub Pages SPA fallback
        run: |
          if [ -f ./dist/index.html ]; then
            cp ./dist/index.html ./dist/404.html
          fi

          # Clean up container
          docker rm temp-container

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
